matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd java
      install:
        - ./mvnw test-compile -DskipTests
      script:
        - ./mvnw test jacoco:report
notifications:
  email: false