name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["14"]
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Build with Maven
        run: mvn -f java/pom.xml -B clean verify
